### PR TITLE
Remove session close exception

### PR DESCRIPTION
**Pull request by vs74**
While performing segmentation though ADS performs segmentation it throws the following session closed exception. This quick PR aims to resolve this issue.
Screen Shot 2019-07-30 at 2 39 19 PM

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
That's odd; this line (`sess.close()`) has been in the software for a very long time (a couple of years at least), and it hasn't caused an issue like yours before. Why do you think this is - is it possible it has to do to with the Keras upgrade?

@perone @alzaia I'm not as well versed in tensorflow as you both; is there any risk (or ressource-wise) to not closing the tensorflow session here?

**Comment by mathieuboudreau** [comment]
Unless there is somewhere that we recently deleted a statement that opens a session - maybe that was in the bulk-delete that was done during the Keras transition?

**Comment by mathieuboudreau** [comment]
Something about this solution just doesn't feel clean to me; maybe we could. take a look at a couple of the recent merges to see when this issue began.

**Comment by vs74** [comment]
It's true unit tests didn't catch (I don't know why) this though at the end of each travis build you could see the following  exception.

**Comment by vs74** [comment]
> That's odd; this line (`sess.close()`) has been in the software for a very long time (a couple of years at least), and it hasn't caused an issue like yours before. Why do you think this is - is it possible it has to do to with the Keras upgrade?
> 
> @perone @alzaia I'm not as well versed in tensorflow as you both; is there any risk (or ressource-wise) to not closing the tensorflow session here?

When we were on `TensorFlow 1.3.0` we were not encountering this exception but since when  we shifted to `TensorFlow 1.13.1` this error came into picture.

**Comment by mathieuboudreau** [comment]
Yup I just saw that while comparing Travis logs. It means that something about how tensorflow sessions are started/stopped changed; we should look into that to make sure we're doing it the proper way.

**Pull request merged**
