### PR TITLE
Integrate Simeon's model with FSLeyes and CLI

### PR DESCRIPTION
**Pull request by vs74**
This PR aims to integrate Simeon's model trained by @mariehbourget on peripheral nerves images. 

**DONE**
- [x] Download model through ADS
- [x] Integrate the new model with FSLeyes
- [x] Upload Model on OSF
- [x] Add tests 
- [x] Implement the new model in CLI.

**TESTING**
1. Navigate to the shared data directory. I'll share the data on Slack through which the segmentation by FSLeyes and 
CLI can be tested

2. In the shared directory, go to the **testing** directory. In the **testing** directory, download one of the images you wish to segment.

3. Simeon's model which is uploaded on OSF is **model_12**. So for each of the images, you will see segmented masks of **model_12**. The name of the segmented mask has the **optimal pixel size** which gives the best segmentations. Use 
should use this pixel size.

a)  **CLI Usage :** `axondeepseg -t OM -i image_name.png -s pixel_size -o 50 -v 3`
b)  **FSLeyes:**  Load the image in FSLeyes and select the modality as `model_seg_pns_bf`. Then select the button `Apply ADS prediction model`. 

For validating the segmentation, you can compare the segmentation done by either FSLeyes or CLI with that of the shared segmentation of the image done by @mariehbourget located under the same testing image directory.

**PS**: I've modified the testing instructions as suggested by @mariehbourget. Thanks for the suggestion.

### CODE REVIEW

**Comment by mariehbourget** [comment]
Following ivadomed convention `model_task_animal_region_contrast`, I suggest we name the model `model_seg_pns_bf`.

`pns` is for peripheral nervous system and `bf` is for bright field (from ours BIDS BEP).
I skipped the animal field since the model will be used on different animal and disease models.
@jcohenadad, it that name ok with you?

Also, as a reference, the model was trained with a general pixel size of 0.1 micrometer per pixel.

**Comment by mariehbourget** [comment]
The model is now on OSF [here](https://osf.io/hfeu2/).

**Comment by vs74** [comment]
Thanks @mariehbourget for updating me about the models being uploaded on OSF. I'll now start working on this PR.

**Comment by vs74** [comment]
I've a question in regards to this PR: apart from the FSLeyes support to segment the images, do we also wish to provide CLI support for the Simeon's model?

**Comment by mariehbourget** [comment]
> I've a question in regards to this PR: apart from the FSLeyes support to segment the images, do we also wish to provide CLI support for the Simeon's model?

Yes, I think we should integrate it as a third default model in CLI as well.

**Comment by vs74** [comment]
> Yes, I think we should integrate it as a third default model in CLI as well.

Since the model is of bright field optical microscopy, should we name it as **OM** (Optical Microscopy) while calling ADS CLI for segmenting peripheral nerves images?

**Comment by vs74** [comment]
This PR is ready for review. The tests are failing because of PR #452

**Comment by mariehbourget** [comment]
> 3\. Simeon's model which is uploaded on OSF is **model_12**. So for each of the images, you will see segmented masks of **model_12**. The name of the segmented mask has the **optimal pixel size** which gives the best segmentations. Use
>     should use this pixel size.
> 
> a) **CLI Usage :** `axondeepseg -t OM -i image_name.png -s pixel_size`

As a precision for testing:
The myelin masks in the share directory were segmented with an overlap_value of 50. In CLI, add the flag `-o 50` to obtain the same result.
Also, because the images are very large, I recommend adding the verbose flag `-v 3` to see the progress.

**Review by mariehbourget — DISMISSED** [review]
The PR looks good to me, thanks @vs74!
I tested on image 5 and got the same results as the reference in CLI with overlap 50.
In FSLeyes, the result is slightly different because of the default overlap of 25 which will be address in issue #458.

I would wait for @mathieuboudreau review before merging to have another pair of eyes on this.

**Comment by vs74** [comment]
@mathieuboudreau I can see that you have uploaded the model on OSF; thanks for that. I've modified the model version in the codebase and cleaned the code, so it is ready for review.

**Comment by mathieuboudreau** [comment]
@vs74 @mariehbourget I'm trying to test this PR/model, however the model uploaded to OSF doesn't include a test dataset/image. @mariehbourget is it possible to upload one? Otherwise, I'm not sure how to test this PR.

**Review by mathieuboudreau — APPROVED** [review]
I tested it with FSLeyes the feature appears to work as expected! I tested it with the CLI and it fails, but that's because I'm on a Mac and #411 .

Thanks a lot!

**Pull request merged**
