### PR TITLE
Release version 3.2.0

### PR DESCRIPTION
**Pull request by jcohenadad**
- Downgraded __ini__ from 3.2 to 3.1 because there was never a 3.1 version

TODO

- Add tags for each PR of 3.1
- Update CHANGELOG in preparation for 3.1
- Update python version requirement on RTD
- Change file name to stick to convention: CHANGELOG --> CHANGES

### CODE REVIEW

**Comment by mariehbourget** [comment]
In the last meeting, we found out that version 3.1 (intended on April 15, 2020, PR #294) and 3.2 (intended on June 22, 2020 in PR #307) had never been officially released on github (latest release is 3.0 on March 13, 2020).
We opened this PR in order to release the current version as the official 3.1 version.
We also removed the "Create a wheel package and uploaded it to PyPI" instructions from the wiki for new release.

However, I found that a version 3.1 was released on PyPI [here](https://pypi.org/project/AxonDeepSeg/) on April 15.

Are we still maintaining versions on PyPI? If so, how can we manage the current difference of version between github and PyPI?

**Comment by jcohenadad** [comment]
> Are we still maintaining versions on PyPI? If so, how can we manage the current difference of version between github and PyPI?

i don't think we are. @mathieuboudreau can confirm

**Comment by mathieuboudreau** [comment]
> > Are we still maintaining versions on PyPI? If so, how can we manage the current difference of version between github and PyPI?
> 
> i don't think we are. @mathieuboudreau can confirm

No, we decided to stop / place that feature on hold at a previous meeting if I recall. It was hard to maintain with users vs. just making them download from github, but we can revisit it if you think it's warranted.

**Comment by mariehbourget** [comment]
Ok, I'll remove the stable release pip instructions in the doc.

But I just want to point out that the latest release 3.1 on PyPI from April 15 will be different from the 3.1 release on github. Shouldn't we skip 3.1 on github and release 3.2 instead?

**Comment by jcohenadad** [comment]
> latest release 3.1 on PyPI from April 15 will be different from the 3.1 release on github.

we should forget about PypI (for now), and be consistent with our GH release (ie: next release should be 3.0, because 3.1 never existed)

**Comment by mariehbourget** [comment]
On PyPI, we cannot completely hide/block download for a release, we have 2 options:
1) Remove completely the release 3.1 without the possibility to re-release it under the same number.
2) Yank the release i.e. it will be ignored when installing with pip unless the user install this exact version (`axondeepseg==3.1`).

Note: the PyPI 3.1 release works as expected with a python 3.6 environment.

So, our options for the next release on github are:
1) Yank version 3.1 on PyPI and release new 3.1 version on github.
2) Release version 3.2 on github (skip 3.1).
3) Release version 3.2 on github (skiip 3.1) and yank version 3.1 on PyPI.

Also, I notice that the project page of axondeepseg on PyPI is not displaying properly (images and section titles). I don't know why, as far as I know, I haven't change anything on the page.

**Comment by jcohenadad** [comment]
> On PyPI, we cannot completely hide/block download for a release, we have 2 options:

can we close the project on pypi (and reopen it later)?

**Comment by mathieuboudreau** [comment]
I would vote for : `Release version 3.2 on github (skip 3.1) and yank version 3.1 on PyPI.` if we can't pause" the project like Julien is suggesting.

**Comment by mariehbourget** [comment]
> can we close the project on pypi (and reopen it later)?

I don't think so. The only option I found is to Delete the project which irreversibly delete all the releases and make the project name available for other pypi users.

**Comment by jcohenadad** [comment]
> > can we close the project on pypi (and reopen it later)?
> 
> I don't think so. The only option I found is to Delete the project which irreversibly delete all the releases and make the project name available for other pypi users.

i would be ok with that, given that pypi should not be used right now (and it would be an unlikely coincidence if there would be another project called axondeepseg, no?)

**Comment by mariehbourget** [comment]
> > > can we close the project on pypi (and reopen it later)?
> > 
> > 
> > I don't think so. The only option I found is to Delete the project which irreversibly delete all the releases and make the project name available for other pypi users.
> 
> i would be ok with that, given that pypi should not be used right now (and it would be an unlikely coincidence if there would be another project called axondeepseg, no?)

that could break other users code if it depends on the package, no?

**Comment by jcohenadad** [comment]
> that could break other users code if it depends on the package, no?

yes but:
- i don't think many people in the world are concerned
- we might want to break their workflow (given that the version is old), so: it will break, then they will go on the GH ADS repos and figure out how to get the up to date version

**Comment by mariehbourget** [comment]
> We could delete and re-register (to save the name)?

Yes we could, but I think we will not be able to re-upload our old release if we want to, see: https://pypi.org/help/#file-name-reuse

**Comment by jcohenadad** [comment]
> Yes we could, but I think we will not be able to re-upload our old release 

not a problem

**Comment by mariehbourget** [comment]
As discussed in meeting, we will switch to MAJOR.MINOR.PATCH naming for new releases.
This release will be 3.2.0.
We will continue to maintain PyPI release through automatic PyPI package creation with github action (issue #353)

TODO
- [ ] - Set `__init__.py` to 3.2.0
- [ ] - Update python version requirement on RTD
- [ ] - Rename next milestone to 3.2.0
- [ ] - Add tags for each PR of 3.2.0
- [ ] - Change file name to stick to convention: CHANGELOG --> CHANGES
- [ ] - Update CHANGELOG in preparation for 3.2.0
- [ ] - Setup Github Action for automatic PyPI package creation

**Comment by jcohenadad** [comment]
> * [ ]  - Change file name to stick to convention: CHANGELOG --> CHANGES
> *

most of our projects (SCT, ivadomed) use `CHANGES.md` instead of `CHANGES`. Don't we want to add the .md extension? What convention are you referring to?

**Comment by mariehbourget** [comment]
> most of our projects (SCT, ivadomed) use `CHANGES.md` instead of `CHANGES`. Don't we want to add the .md extension? What convention are you referring to?

The convention for the changelog to be named `CHANGES.md`, instead of the current `CHANGELOG.md` in ADS. I edited to TO DO list above to clarify.

**Comment by mathieuboudreau** [comment]
@mariehbourget Stoyan's PR has been merged, so I think we can proceed with this one.

**Comment by mariehbourget** [comment]
> @mariehbourget Stoyan's PR has been merged, so I think we can proceed with this one.

Thanks @mathieuboudreau 
I updated the changelog to include Stoyan's PR and renamed it CHANGES.md.

The only thing left before we can merge would be to setup Github Actions for automatic release on PyPI (issue #353).

**Comment by mariehbourget** [comment]
As discussed, I renamed CHANGES.md to CHANGELOG.md.
We won't use github actions for this release, I will create the release on github and upload to PyPI after the merge.

**Comment by mariehbourget** [comment]
@mathieuboudreau, do you want to review before I merge or do I approve my own PR?

**Review by mathieuboudreau — APPROVED** [review]
Approved per our discussions during our group meeting today. Love the detailed changelog!

**Comment by mathieuboudreau** [comment]
> @mathieuboudreau, do you want to review before I merge or do I approve my own PR?

I'll give you the honour of clicking merge, thanks @mariehbourget !

**Comment by mariehbourget** [comment]
Thanks @mathieuboudreau, the release on github is done.
I have a question for PyPI, I update my master branch, do I have more clean-up to do before creating the wheel? (ex: untracked files?)

**Pull request merged**
