### PR TITLE
Refactor the code for the settings menu

### LINKED ISSUE #475: FSLeyes: Add more settings to the settings menu
This issue is a sequel to #458 
Other settings to add:
- A way to change the model resolution (to deal with #334 and related to #428).
- Axon shape selection
- A case that displays the pixel size
- Suffixes that determine the type of mask when loading them

Also the settings menu code needs refactoring, I suggest moving everything related to the settings & settings menu in a new class.

### PR DESCRIPTION
**Pull request by Stoyan-I-A**
## Checklist

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [X] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer
- [ ] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description
- The goal of this PR is to remove cluttering in the code for the `ADScontrol `class
- The code that handles the settings and the settings menu of the FSLeyes plugin has been moved to a new class called `ADSsettings`
- This PR does not add or remove any existing features.

## Linked issues
Resolves the refactoring part of #475

### CODE REVIEW

**Comment by Stoyan-I-A** [comment]
Can someone review this PR?

**Comment by vasudev-sharma** [comment]
I tried reviewing this PR, but unfortunately due because of issue #https://github.com/neuropoly/axondeepseg/issues/521, ADS pannel doesn't show up in the` Settings > Ortho View 1 ` for me

Check here
image

So, can anyone else review this PR?

**Comment by Stoyan-I-A** [comment]
🤔That's wierd. Does this happen with the plugin in the master branch of AxonDeepSeg?

**Review by mariehbourget — APPROVED** [review]
Thanks @Stoyan-I-A! 
I was able to checkout the branch, install the new plugin version and run it in FSLeyes as usual on Ubuntu 20.04 in WSL1. Everything is working as expected with the plugin and settings menu.

**Comment by Stoyan-I-A** [comment]
Thank you @mariehbourget.

Does anyone know if there's a way to re-trigger the `readthedocs` build? It failed and I don't know why.

**Comment by vasudev-sharma** [comment]
> Thank you @mariehbourget.
> 
> Does anyone know if there's a way to re-trigger the `readthedocs` build? It failed and I don't know why. (I haven't modified the docs file.)

The reason the doc build failed was because recently Fastly CDN was down and due to that a lot of services such as Stackoverflow, Reddit, GitHub, Twitch and many others were down. I updated this PR to latest mastest branch commit in commit e263f5c at that time when Fastly was down. 

It was not only that the docs build that failed; the tests were failing too due to this. I retriggered the tests, so you can see the tests passing. However, I wasn't aware how to retrigger the docs build, so they are in the same state. Don't worry about the docs build failing, we just have to re-run the build and it would pass.

**Comment by vasudev-sharma** [comment]
Looks like for this PR, the docs build was not trigerred ( see [here](https://readthedocs.org/projects/axondeepseg/builds/13956254/)).

**Comment by Stoyan-I-A** [comment]
I just pushed a dummy change to retrigger the doc build.

**Review by mariehbourget — APPROVED** [review]
Thanks @Stoyan-I-A, everything working as expected.
Sorry for the delay with the review.

**Pull request merged**
