### PR TITLE
Updated logo

### LINKED ISSUE #171: Make nice logo and add to readthedocs
Title is pretty self-explanatory

### PR DESCRIPTION
**Pull request by jcohenadad**
Fixes #171 

Todo before merging: check doc appearance with new logo

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
How's this in terms of the readme?

Capture d’écran 2019-03-12 à 14 28 12

**Comment by mathieuboudreau** [comment]
@jcohenadad ReadTheDocs isn't being updated to include this branch because you have a UTF8 character in the branch name (`-`): see https://github.com/rtfd/readthedocs.org/issues/1617

We can't preview it directly off of this branch; I'll branch out from this one and rename it to a RTD friendly name so we can preview it on that one.

**Comment by mathieuboudreau** [comment]
Hmm, other branch names with that characters are in the RTD list (below), so maybe we just have to be patient.

Capture d’écran 2019-03-12 à 14 36 19

**Comment by jcohenadad** [comment]
> ReadTheDocs isn't being updated to include this branch because you have a UTF8 character in the branch name (-): see rtfd/readthedocs.org#1617

So, what are the authorized chars? ASCII? (hyphen is in ASCII-- so maybe my keyboard does not produce the same hyphen)

**Comment by mathieuboudreau** [comment]
That's an old issue that I found on their repo, and since I just noticed we have branches that have those characters on RTD (see photo just above), they must have updated it to be compatible with them since that issue. So not sure why RTD isn't updating for this particular branch, or why it's taking so long.

**Comment by mathieuboudreau** [comment]
@jcohenadad see here for preview: https://axondeepseg.readthedocs.io/en/jca-171-logo/

**Comment by jcohenadad** [comment]
hum, not great. I need to produce a logo without alpha transparency in the non-white pixels

**Comment by mathieuboudreau** [comment]
Maybe it's the background color that's the issue? The alpha logo looks fine with a white background (see the readme screenshot above) What if we changed it to white.

**Comment by jcohenadad** [comment]
> Maybe it's the background color that's the issue?

is it (easily) possible to change the background color in RTD?  it guess it must be a preference/settings type of things?

**Comment by jcohenadad** [comment]
@mathieuboudreau do avoid playing with RTD template, can you try with this updated image: https://github.com/neuropoly/axondeepseg/pull/185/commits/b98fa0153ab72765c8b3bb105167d76d22d6a9cf#diff-161348ed531bb8abb2a231ff1917c6d3?

**Comment by mathieuboudreau** [comment]
Closer, but there's white speckles:

Capture d’écran 2019-03-12 à 16 51 57

**Comment by jcohenadad** [comment]
ah that's annoying. I have a pdf version. We could try with that-- or maybe convert the pdf as a svg (that's what RTD uses for its own RTD ;-) ). Any insight as to what would work best?

**Comment by mathieuboudreau** [comment]
If you have those easily available, just upload them all here and I'll do a comparison between the three, then we can cleanup the ones we don't use. The other solution I'd recommend is simply to avoid alpha altogether and use a white background for the image (I think you have that one up too? I can compare that one as well).

**Comment by jcohenadad** [comment]
@mathieuboudreau the png-noalpha and pdf are already in my branch: https://github.com/neuropoly/axondeepseg/tree/jca/171-logo/docs/source/_static

i'll generate the svg asap

**Comment by jcohenadad** [comment]
@mathieuboudreau svg version added

**Comment by mathieuboudreau** [comment]
@jcohenadad thanks for the svg! I went in it with Inkscape and cleaned it up a bit (there were some old red & blue cicles behind the grey ones), and regenerated a PNG with transparency. How does this one look?

Capture d’écran 2019-03-12 à 19 25 38

**Pull request merged**
