### PR TITLE
Use the myelin centroids as seed points for the floodfill

### LINKED ISSUE #384: Improve procedure for manual correction of output segmentations
### Context

Currently, the [procedure for correcting output segmentations](https://axondeepseg.readthedocs.io/en/latest/documentation.html#manual-correction-of-segmentation-masks) is based on the filling of myelin masks, based on a watershed initialized by the center of mass (COM) of the axons.

This is prone to issues because sometimes, lots of "wrong" single axon pixels are spread out at many places in the output segmentation image.  

### Suggestion

A more efficient workflow would consist in *not* relying on the axon mask, and only on the myelin mask (less work to do):
- Manually fixing the myelin mask only (ie: closing it, adjusting borders, remove isolated pixels)
- Estimate COM of the myelin (not axons)
- Use that COM to run the watershed.

### PR DESCRIPTION
**Pull request by Stoyan-I-A**
Check this presentation for more information on the tool: https://docs.google.com/presentation/d/1aRl7C1IzzdhXzUBHk4tnIzU3L2r-DJ1540hnQdivzJE/edit#slide=id.p

fixes #384 

In FSLeyes, the axon mask is no longer required to use the "Fill axons" button

### CODE REVIEW

**Comment by Stoyan-I-A** [comment]
@mariehbourget You can use this to fill the axons in the Simeon images. 
Remember,
- No open myelin
- No touching myelin

**Comment by Stoyan-I-A** [comment]
By the way, in #396 , there's an exemple where this feature might not suit the user.

**Comment by mariehbourget** [comment]
Thank you @Stoyan-I-A!

I tried the feature, it works well, but there are a few axons where the “Fill axons” fills the myelin itself instead of the interior part. For those axons, the center is black, and the myelin is both blue (in the axon mask) and red (in the myelin mask).
fsleyes_axon_example_50 fsleyes_myelin_example_50

When exporting, the overlap is detected so the “myelin” mask is fine, but those axons are missing on the “axon” and “axonmyelin” masks.

I’m not sure if I can share the myelin mask I used here, so I’ll send you a link privately if you want to test it on your side.

For the time being, I was able to correct those few axons manually.

As you mentioned, the “no touching myelin” might be a problem in several cases, with our datasets and other users datasets. In my opinion, the feature is worth pursuing because it simplify greatly the manual correction procedure, however, we should keep looking for solutions with touching myelin before changing the behavior.

**Comment by Stoyan-I-A** [comment]
For the axon on the top left, this happens because the center of mass of the myelin object is actually on the myelin itself.
image
I am not sure how we should deal with those cases.

**Comment by Stoyan-I-A** [comment]
Same deal with the other one
image

**Comment by jcohenadad** [comment]
> For the axon on the top left, this happens because the center of mass of the myelin object is actually on the myelin itself.

Hum, that's an interesting problem. IIUC, you only need a single pixel _inside_ the myelin, to start the flood fill process, right? So, it doesn't necessarily need to be at the center. If that's the case, how about applying a closure of the myelin mask, followed by the subtraction between the closure and the myelin mask --> the output should _only_ give pixels inside the myelin (ie: which are axons). Then, pick one of those pixels as the seed for the flood fill. Does that make sense?

**Comment by jcohenadad** [comment]
An additional comment about the problem of touching myelin: how about applying a [squeletonization](https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html) on the myelin masks, followed by the finding of seeds that will be used by the flood fill algo (this seed finding could be center of mass, or another method as pointed out in https://github.com/neuropoly/axondeepseg/pull/397#issuecomment-730465543).

**Comment by Stoyan-I-A** [comment]
> you only need a single pixel inside the myelin, to start the flood fill process, right?

Yes.

I have done a bit of experimentation with this myelin mask:
image

Here's what a closing operation does to the mask:
image

With the two images overlapped:
image

It is definitely something we could work with, but I felt like there were probably easier solutions. So I looked for alternatives and found the [remove_small_holes](https://scikit-image.org/docs/dev/api/skimage.morphology.html#remove-small-holes) function from scikit-image. With this, I can define how large the maximum area of an axon should be, and it will fill the image as long as the myelin is closed.

Here's what it looks like if I set the maximum area of one axon to about 10% of the total image size:
image

With the two images overlapped:
image

So far, this looks nice.

**Comment by Stoyan-I-A** [comment]
I am closing this PR because we chose to use the remove_small_holes for filling the myelin mask with axon objects. The development of this tool is in #585.

**Pull request closed without merging**
