### PR TITLE
Add tutorial video link in RTD

### LINKED ISSUE #492: FSLeyes video tutorial has disappeared from RTD
I just notice that the video tutorial for FSLeyes is no longer in RTD.

Based on the rendered version of the docs in recent PRs, the link to the tutorial was present in PR #474 merged 13 days ago, but not in PR #476 merged 7 days ago.

I'm not sure what happened here because PR #476 did not change the `documentation.rst` file and I can't find PRs that were merged between those two.
Any ideas?

### PR DESCRIPTION
**Pull request by mariehbourget**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer
- [x] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description
This PR add the link to the video tutorial in RTD and the note about the ADScontrol tab not appearing after first installing the plugin. Both were removed by mistake in #452.

## Linked issues
Fixes #492

### CODE REVIEW

**Review by mathieuboudreau — DISMISSED** [review]
Seems to work great (https://axondeepseg.readthedocs.io/en/mhb-492-add-tutorial-link-rtd/documentation.html#graphical-user-interface-gui-optional), thanks @mariehbourget !

**Review by vs74 — DISMISSED** [review]
LGTM, thanks @mariehbourget for noticing this.

**Comment by mathieuboudreau** [comment]
Although @mariehbourget - maybe we should update the video or split it, because I think I removed it initially because now it includes outdated installation instructions.

**Comment by mariehbourget** [comment]
> Although @mariehbourget - maybe we should update the video or split it, because I think I removed it initially because now it includes outdated installation instructions.

You are right, we should at least split it to remove the first part and start at around 4:10 with the GUI part.
We could wait until the circle/ellipse features is integrated to do a new one.

**Comment by mathieuboudreau** [comment]
@mariehbourget the video has been split. It should be the same link: https://www.youtube.com/watch?v=dz2LqQ5LpIo

**Comment by mariehbourget** [comment]
@mathieuboudreau, for me the video doesn't play correctly. I have the visual of the original first 4 minutes, with the sound of the original 4 last minutes.

**Comment by mathieuboudreau** [comment]
Huh darn! I tried using youtube's trimming tool but seems like it's buggy. I'll do it again locally on my pc and reupload it

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mathieuboudreau** [comment]
Huh, I was sure I replied by email, but it seems GitHub didn't catch it.

@mariehbourget I uploaded the revised cut of the video a couple of weeks ago, here it is: https://studio.youtube.com/video/qzWeG5vaVyo/edit

**Comment by mathieuboudreau** [comment]
I copied the link just for me, here is the public link: https://youtu.be/qzWeG5vaVyo

**Comment by mariehbourget** [comment]
Thanks @mathieuboudreau, I updated the link.
The PR is ready for re-review.

**Review by mathieuboudreau — APPROVED** [review]

**Pull request merged**
