### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by nekohayo**
The first two commits are trivial changes.
The third commit could spark World War Vi.

### CODE REVIEW

**Comment by jcohenadad** [comment]
I'm in favour of https://github.com/neuropoly/axondeepseg/pull/433/commits/fff01dc248006ae0a8054eeea916e6c3d1c76e1b, but I would like that everyone in the lab agrees to it (for harmonizing practices in the lab), and if so, we should update the internal cross-project documentation. @mathieuboudreau @joshuacwnewton @kousu do you have an opinion on this?

**Comment by joshuacwnewton** [comment]
> I'm in favour of [fff01dc](https://github.com/neuropoly/axondeepseg/commit/fff01dc248006ae0a8054eeea916e6c3d1c76e1b), but I would like that everyone in the lab agrees to it (for harmonizing practices in the lab), and if so, we should update the internal cross-project documentation. @mathieuboudreau @joshuacwnewton @kousu do you have an opinion on this?

I like the changes @nekohayo has made. And, funny enough, I have already been writing this way when doing the SCT Course documentation pages! When writing pure plaintext/markup (`.txt`, `.rst`, `.md`, `.html`, etc.), I prefer to let my editor do the wrapping instead of adding breaks to restrict line lengths.

But, this is also a matter of taste, and there are [lots of different opinions](https://about.gitlab.com/blog/2016/10/11/wrapping-text/). So, I'm happy to hear other thoughts as well.

**Comment by mathieuboudreau** [comment]
>The third commit could spark World War Vi.

>@mathieuboudreau @joshuacwnewton @kousu do you have an opinion on this?

>But, this is also a matter of taste, and there are lots of different opinions. So, I'm happy to hear other thoughts as well.

aUbk9ha

**Comment by kousu** [comment]
I also let my editor wrap for me. I am happy to do that too.

**Review by jcohenadad — APPROVED** [review]
@nekohayo @joshuacwnewton it would be great to harmonize dynamic line wrapping practice in the lab-- could you please disseminate this practice across all our internal doc? thanks 🙏

**Comment by joshuacwnewton** [comment]
Hrm... the `Travis CI - Branch` CI check that's pending forever seems to be because this PR was [created from a fork](https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829/8).

> “Branch check” runs on your fork. Because you don’t have Travis CI activated on your fork, the check never runs, and the check never arrives.

Options:
1. @nekohayo creates this PR from a `neuropoly` branch.
2. @nekohayo enables Travis for the fork.
3. We turn off "Travis CI - Branch" as a required check, and stick just with "Travis CI - Pull Request"

Thoughts? I'm leaning towards 3), as that's what we did with SCT.

**Comment by mathieuboudreau** [comment]
> Hrm... the `Travis CI - Branch` CI check that's pending forever seems to be because this PR was [created from a fork](https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829/8).
> 
> > “Branch check” runs on your fork. Because you don’t have Travis CI activated on your fork, the check never runs, and the check never arrives.
> 
> Options:
> 
> 1. @nekohayo creates this PR from a `neuropoly` branch.
> 2. @nekohayo enables Travis for the fork.
> 3. We turn off "Travis CI - Branch" as a required check, and stick just with "Travis CI - Pull Request"
> 
> Thoughts? I'm leaning towards 3), as that's what we did with SCT.

I can use admin privileges to override this and merge if you'd like, since the PR test passed. We don't often get fork PR's, and when we do we merge them to another branch first and not master to solve this, but we could remove that check as well if someone points me to where to remove the branch check.

**Pull request merged**
