### PR TITLE
[BUG] Switch to nearest neighbour interpolation when creating patches of mask images.

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Related to #139 and our discussion at the last group meeting.

Changes:

* Created a new function to check the number of unique values in an image, and what those values are, and add test.
* Switch to nearest neighbour interpolation when creating patches of mask images (`rescale()` from scikit-image needs to be passed `order=0` to do this).
* Add test that masks created by the data management tool output patches with only three unique values (without the above fix, this test failed **!**).

There is likely several other spots in the code that might be introducing shades of grey (e.g. during data augmentation), but I think that this PR will be a large leap forward in the right direction enough that it warrants to be merged ASAP.

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
* [ ] Note to myself: send raw image to @vs74  so that he may test it in this branch

**Comment by mathieuboudreau** [comment]
@vs74 there are already files ready and formatted (named) the correct way in the project that you can use to test this branch with. They are located [here]()

All you need to do is run the following script in your `master` branch:

```python
from pathlib import Path
from AxonDeepSeg.data_management.dataset_building import *

test_data = Path("/Users/mathieuboudreau/neuropoly/github/ads_grey/test/__test_files__/__test_patch_files__/")
raw_images = test_data / 'raw'
patched_output = test_data / 'patch'
raw_img_to_patches(str(raw_images), str(patched_output))
```

Substituting `/Users/mathieuboudreau/neuropoly/github/ads_grey` for your full path to your AxonDeepSeg clone.

Look at the mask files in the patch folders using an image editor: at the boundaries, they have values between the three classes (0, 128, 255).

Then, checkout the `mask_interpolation` branch (this PR), and rerun the script. Check out the mask files in the patch folders, and all pixels should only contain one of those three classes

**Comment by vs74** [comment]
Thank you, @mathieuboudreau for the detailed instructions. I will review this PR.

**Comment by vs74** [comment]
This PR is working as expected.

**Pull request merged**
