### PR TITLE
[REF] Revert tensorflow req to 1.3.0 and remove tifffile requirement

### PR DESCRIPTION
**Pull request by mathieuboudreau**
As pointed out by @perone, tensorflow might behave differently for newer versions, so we might as well stick with 1.3.0 as originally intended (although before, we had a req of >= 1.3.0, so whatever was installed at any given time was the most up to date version). I had fixed it to 1.9.0 as it was the most up-to-date version at the time (thus, the one being installed anyways). Also, the CUDA libraries installed on Rosenberg at the moment (or at least, for me as a user) aren't compatible with tensorflow versions >= 1.5.0.

Also removing the tifffile requirement. That one was added recently because imageio shouts warnings for tiffiles that it's not optimized for speed without tifffile installed (see: https://github.com/imageio/imageio/issues/350). This worked fine for me on my local (MacOSX), and on Travis tests (Linux), however when I tried installing the pip requirement on Rosenberg, C-librarie errors were thrown:

<details>

```

Building wheels for collected packages: tifffile
  Running setup.py bdist_wheel for tifffile ... error
  Complete output from command /home/mabou_local/venv_ads2/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_bumnz1q/tifffile/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-b2cvauy8 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/tifffile
  copying tifffile/__init__.py -> build/lib.linux-x86_64-3.6/tifffile
  copying tifffile/tifffile.py -> build/lib.linux-x86_64-3.6/tifffile
  running egg_info
  writing tifffile.egg-info/PKG-INFO
  writing dependency_links to tifffile.egg-info/dependency_links.txt
  writing requirements to tifffile.egg-info/requires.txt
  writing top-level names to tifffile.egg-info/top_level.txt
  reading manifest file 'tifffile.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'tifffile.egg-info/SOURCES.txt'
  copying tifffile/_tifffile.c -> build/lib.linux-x86_64-3.6/tifffile
  running build_ext
  building 'tifffile._tifffile' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/tifffile
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/mabou_local/venv_ads2/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c tifffile/_tifffile.c -o build/temp.linux-x86_64-3.6/tifffile/_tifffile.o
  tifffile/_tifffile.c:73:20: erreur fatale: Python.h : Aucun fichier ou dossier de ce type
   #include "Python.h"
                      ^
  compilation terminée.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for tifffile
  Running setup.py clean for tifffile
Failed to build tifffile
Installing collected packages: tensorflow, tifffile, AxonDeepSeg
  Found existing installation: tifffile 2018.10.18
    Uninstalling tifffile-2018.10.18:
      Successfully uninstalled tifffile-2018.10.18
  Running setup.py install for tifffile ... error
    Complete output from command /home/mabou_local/venv_ads2/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_bumnz1q/tifffile/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kh13odk8/install-record.txt --single-version-externally-managed --compile --install-headers /home/mabou_local/venv_ads2/include/site/python3.6/tifffile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/tifffile
    copying tifffile/__init__.py -> build/lib.linux-x86_64-3.6/tifffile
    copying tifffile/tifffile.py -> build/lib.linux-x86_64-3.6/tifffile
    running egg_info
    writing tifffile.egg-info/PKG-INFO
    writing dependency_links to tifffile.egg-info/dependency_links.txt
    writing requirements to tifffile.egg-info/requires.txt
    writing top-level names to tifffile.egg-info/top_level.txt
    reading manifest file 'tifffile.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'tifffile.egg-info/SOURCES.txt'
    copying tifffile/_tifffile.c -> build/lib.linux-x86_64-3.6/tifffile
    running build_ext
    building 'tifffile._tifffile' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/tifffile
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/mabou_local/venv_ads2/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c tifffile/_tifffile.c -o build/temp.linux-x86_64-3.6/tifffile/_tifffile.o
    tifffile/_tifffile.c:73:20: erreur fatale: Python.h : Aucun fichier ou dossier de ce type
     #include "Python.h"
                        ^
    compilation terminée.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of tifffile
Command "/home/mabou_local/venv_ads2/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_bumnz1q/tifffile/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kh13odk8/install-record.txt --single-version-externally-managed --compile --install-headers /home/mabou_local/venv_ads2/include/site/python3.6/tifffile" failed with error code 1 in /tmp/pip-install-_bumnz1q/tifffile/


```

</details></p>

We'll just have to bear with the warnings until imageio gets updated and this issue is resolved. Warnings are only shown to users for tiff files, ans since most of our files are png, this isn't too much of a nuissance (I hope).

### CODE REVIEW

**Comment by perone** [comment]
This warning goes away if you use Anaconda and inside a conda environment ? I really recommend using Anaconda and the conda environments on Rosenberg, it usually solves all these issues with Python sources, virtual env binaries, etc.

**Comment by mathieuboudreau** [comment]
@perone Re: Anaconda/Conda

I completely agree – I always prefer using Anaconda + conda's venv instead of the native python venv, that's what I use on my laptop. However, the I couldn't see Anaconda/conda in my path for the environment that was setup to my new user account on Rosenberg by @alexfoias . I tried installing miniconda and using conda to create my venv, however because of my privilege limitations, it would only allow me to install my venv using the --user flag, which caused some conflict with my default python packages, hence my issue I talked about in slack. If there's a way for me to use Anaconda/conda on Rosenberg, I'd much rather do so (and we should add those instructions to the Rosenberg SOP, as it only gives instructions to use the native virtualenv command).

Re: warnings

Without tifffile installed, but using Anaconda/conda (on my laptop), these warnings appear. I can install tifffile in my conda environment on my local computer without the error that is shown in the `details` above. I can't install tifffile on rosenberg, which appears to be either because of a gcc linking error and/or gcc can't find Python.h.

**Comment by alexfoias** [comment]
@jcohenadad & @mathieuboudreau  I granted him access as sudo

**Comment by perone** [comment]
Just an extra note: you can use the environments from conda itself (https://conda.io/docs/user-guide/tasks/manage-environments.html) instead of using virtualenvs.

**Comment by jcohenadad** [comment]
i would not venture in trying to get a py3 venv from a conda2 install. I think we should just install conda3.

**Comment by mathieuboudreau** [comment]
@jcohenadad Ok! I just know that when Anaconda 3 is installed (for me at least), you can create a virtual environment in almost any Python version available. But then yes, we should have an Anaconda3 installation available on Rosenberg to create venvs for projects using Python 3+ (like ADS in its current state).

**Comment by perone** [comment]
What I usually do is:
- Install conda3 like in `/home/user/anaconda3`;
- Make sure that this path is on the `PATH` and not the system anaconda or other anaconda conflicting with it;
- Create environment using conda itself

The error you're getting seems to be because your're using system wide conda, I think the best approach is to install your own anaconda for your user, so you can uninstall/install any package you want and it will not be in conflict with anything.

**Comment by mathieuboudreau** [comment]
@perone thanks! I tried installing miniconda last week for my user (instead of Anaconda3), and when I tried creating an environment with conda, it said I needed to use the --user flag, which I think gave me some problems. I'll give it another shot with the full Anaconda3 package soon.

Have you done the procedure above on Rosenberg?

**Comment by perone** [comment]
Yes, I installed anaconda3 on my home user folder, you can use `which` later to check from where your conda is being executed:

```
[chper_local@rosenberg ~]$ which conda
~/anaconda3/bin/conda
```

See that in my case, the `conda` comes from my anaconda3 distribution.

**Comment by mathieuboudreau** [comment]
Cool! 

Might it be better to simply have a shared anaconda3 folder that's available to all users like we have for anaconda2, since we should be working on conda virtual environments anyways? It could save on space, and the installation step for new users. I'm indifferent personally though for my own use.

**Comment by jcohenadad** [comment]
actually yes, that makes sense. Let's have a global anaconda3 install (and in the SOP, mention that each new student should work under venv)

**Comment by mathieuboudreau** [comment]
@alexfoias No I haven't, I held off since you said there might be an issue with the Anaconda2 installation re: my slack message to you. If you can do it, thanks!

**Pull request merged**
