### PR TITLE
Bug: patches myelin thickness calculation

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Resolves a bug discovered by @vs74 in this comment: https://github.com/neuropoly/axondeepseg/pull/399#issuecomment-769028585

Wrote a unit tests that verifies that the myelin thickness calculated using the g-ratio and axon radius results in the same g-ratio when combined with the axon radius, hopefully to avoid this bug in the future.

### CODE REVIEW

**Review by mariehbourget — COMMENTED** [review]
The tests `test_simulate_circular_axon` and `test_simulate_ellipsoidal_axon` are failing. Maybe it is because of the old formula for myelin thickness used [here](https://github.com/neuropoly/axondeepseg/blob/8ce0588381cf90d78ffee1a798e4822502b60d53/test/visualization/test_simulate_axons.py#L57) and [here](https://github.com/neuropoly/axondeepseg/blob/8ce0588381cf90d78ffee1a798e4822502b60d53/test/visualization/test_simulate_axons.py#L117)?

It is also in the `test_saved_file_exists` test [here](https://github.com/neuropoly/axondeepseg/blob/8ce0588381cf90d78ffee1a798e4822502b60d53/test/visualization/test_simulate_axons.py#L176) but doesn't affect the outcome of the test.

**Comment by mathieuboudreau** [comment]
> The tests `test_simulate_circular_axon` and `test_simulate_ellipsoidal_axon` are failing. Maybe it is because of the old formula for myelin thickness used [here](https://github.com/neuropoly/axondeepseg/blob/8ce0588381cf90d78ffee1a798e4822502b60d53/test/visualization/test_simulate_axons.py#L57) and [here](https://github.com/neuropoly/axondeepseg/blob/8ce0588381cf90d78ffee1a798e4822502b60d53/test/visualization/test_simulate_axons.py#L117)?
> 
> It is also in the `test_saved_file_exists` test [here](https://github.com/neuropoly/axondeepseg/blob/8ce0588381cf90d78ffee1a798e4822502b60d53/test/visualization/test_simulate_axons.py#L176) but doesn't affect the outcome of the test.

Good catch! I'll change them ASAP

**Review by mariehbourget — APPROVED** [review]
Looks good to me!
(I assume that the remaining failing tests are because of #441 that has to be merged first)

**Comment by vs74** [comment]
I would like to have this PR merged so I can work with my PR #399. Thanks!!

**Comment by mathieuboudreau** [comment]
> Since PR #441 has been merged, I would like to have this PR merged so I can work with my PR #399. Thanks!!

Force merging now. Errors being thrown are due to #452 not being merged yet.

**Pull request merged**
