### PR TITLE
Fix notebook links in doc

### LINKED ISSUE #412: Links broken for Jupyter Notebooks in RTD
The links in RTD for Jupyter Notebooks have not been updated since the cleaning and renaming of the notebooks in #226.
I'll open a PR to make the changes.

### PR DESCRIPTION
**Pull request by mariehbourget**
Fixes #412

### CODE REVIEW

**Review by mathieuboudreau — APPROVED** [review]
Thanks for catching this @mariehbourget !

I just checked all the links, and they all point to the correct notebook.

However, I ran the Getting Started notebook, and it is broken in MyBinder because the model wasn't downloaded. Can you check locally on your side?

Capture d’écran 2020-12-04 à 11 54 55

Capture d’écran 2020-12-04 à 11 55 09

Regardless, this PR works and I'll approve. We should investigate the other issue in another PR.

**Comment by mariehbourget** [comment]
> However, I ran the Getting Started notebook, and it is broken in MyBinder because the model wasn't downloaded. Can you check locally on your side?

Oups, I had not thought about that!
I have the same error as you. Since the model is not in the repo anymore, I don't think it can work with that notebook. Maybe we could try adding the download in another notebook specific to MyBinder? Or remove that option?

I suggest to remove it for now and open an issue dedicated to bring it back, what do you think?

**Comment by mathieuboudreau** [comment]
> > However, I ran the Getting Started notebook, and it is broken in MyBinder because the model wasn't downloaded. Can you check locally on your side?
> 
> Oups, I had not thought about that!
> I have the same error as you. Since the model is not in the repo anymore, I don't think it can work with that notebook. Maybe we could try adding the download in another notebook specific to MyBinder? Or remove that option?
> 
> I suggest to remove it for now and open an issue dedicated to bring it back, what do you think?

Let's see if it can be quickly fixed, and if it can't then we'll remove it from the doc.

**Comment by mathieuboudreau** [comment]
@mariehbourget I found a solution, and resolved it in #415. We can go ahead and merge this PR as-is.

**Comment by mariehbourget** [comment]
Thanks @mathieuboudreau!

**Pull request merged**
