### PR TITLE
Increase conda timeout to 1 hour

### PR DESCRIPTION
**Pull request by mathieuboudreau**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [ ] I've assigned a reviewer
- [x] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description
Increased the conda timeout to 1 hour to help the scheduled tests from failing due to timeouts

### CODE REVIEW

**Comment by jcohenadad** [comment]
well, my bad 😕
image

**Comment by mathieuboudreau** [comment]
Hum, really don't know why it's breaking. Maybe it's the RAM issue that @Stoyan-I-A mentionned he sometimes encountered on Linux systems?

**Comment by Stoyan-I-A** [comment]
According to the information given by GitHub, the Run fails after 5 minutes.

image

**Comment by Stoyan-I-A** [comment]
I am speculating a little bit, but I believe that if the RAM issue is causing this problem, the environment creating step could be completed during the Run if we remove some heavy packages from the requirements in the `environment.yml` file like `fsleyes=0.33.1`.

**Comment by jcohenadad** [comment]
> Edit: also notice how this phenomenon doesn't occur on the v4-ivadomed branch

now that's interesting

**Comment by mathieuboudreau** [comment]
Ah, great observation!

The branch has a different environment file, thus different requirements. 

Let's put a pause on this PR and see if V4 resolves it as-is.

**Comment by mariehbourget** [comment]
While reviewing #388, I tried installing from scratch on my laptop (Ubuntu 20.04 in WSL1). There is definitely something weird with the conda environment. I got stuck on "Solving environment" for 30 minutes, before the installation started.
In total, it took 39 minutes.

Here is the complete output if that helps:
<details>
<summary> Conda environment</summary>

```
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
| WARNING conda.models.version:get_matcher(531): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
python-3.7.12        | 57.3 MB   | ###################################################################################################### | 100%
toolchain-2.4.0      | 14 KB     | ###################################################################################################### | 100%
pyqt5-sip-4.19.18    | 310 KB    | ###################################################################################################### | 100%
dbus-1.13.6          | 604 KB    | ###################################################################################################### | 100%
absl-py-1.0.0        | 95 KB     | ###################################################################################################### | 100%
certifi-2021.10.8    | 145 KB    | ###################################################################################################### | 100%
sphinx-4.3.2         | 1.5 MB    | ###################################################################################################### | 100%
cryptography-36.0.1  | 1.7 MB    | ###################################################################################################### | 100%
zstd-1.5.1           | 463 KB    | ###################################################################################################### | 100%
pyrsistent-0.18.0    | 90 KB     | ###################################################################################################### | 100%
pandas-1.3.5         | 12.7 MB   | ###################################################################################################### | 100%
openblas-0.3.18      | 10.2 MB   | ###################################################################################################### | 100%
libcurl-7.81.0       | 338 KB    | ###################################################################################################### | 100%
glib-tools-2.70.2    | 105 KB    | ###################################################################################################### | 100%
dataclasses-0.8      | 10 KB     | ###################################################################################################### | 100%
brotlipy-0.7.0       | 342 KB    | ###################################################################################################### | 100%
xorg-libxi-1.7.10    | 46 KB     | ###################################################################################################### | 100%
python_abi-3.7       | 4 KB      | ###################################################################################################### | 100%
libdrm-2.4.109       | 284 KB    | ###################################################################################################### | 100%
ipython-7.31.0       | 1.1 MB    | ###################################################################################################### | 100%
aom-3.2.0            | 5.4 MB    | ###################################################################################################### | 100%
flit-core-3.6.0      | 42 KB     | ###################################################################################################### | 100%
blas-devel-3.9.0     | 12 KB     | ###################################################################################################### | 100%
numpy-1.21.5         | 6.1 MB    | ###################################################################################################### | 100%
xorg-fixesproto-5.0  | 9 KB      | ###################################################################################################### | 100%
libpciaccess-0.16    | 37 KB     | ###################################################################################################### | 100%
markdown-3.3.6       | 67 KB     | ###################################################################################################### | 100%
ipykernel-6.7.0      | 179 KB    | ###################################################################################################### | 100%
toolchain_c_linux-64 | 13 KB     | ###################################################################################################### | 100%
kiwisolver-1.3.2     | 78 KB     | ###################################################################################################### | 100%
pyqtchart-5.12       | 257 KB    | ###################################################################################################### | 100%
x264-1!161.3030      | 2.5 MB    | ###################################################################################################### | 100%
rtree-0.9.7          | 45 KB     | ###################################################################################################### | 100%
qtconsole-5.2.2      | 5 KB      | ###################################################################################################### | 100%
theano-1.0.3         | 3.6 MB    | ###################################################################################################### | 100%
jupyter-1.0.0        | 6 KB      | ###################################################################################################### | 100%
pillow-8.4.0         | 706 KB    | ###################################################################################################### | 100%
jedi-0.18.1          | 997 KB    | ###################################################################################################### | 100%
liblapacke-3.9.0     | 12 KB     | ###################################################################################################### | 100%
gstreamer-1.18.5     | 2.0 MB    | ###################################################################################################### | 100%
toolchain_cxx_linux- | 13 KB     | ###################################################################################################### | 100%
requests-2.27.1      | 53 KB     | ###################################################################################################### | 100%
attrs-21.4.0         | 49 KB     | ###################################################################################################### | 100%
gast-0.5.3           | 20 KB     | ###################################################################################################### | 100%
libvpx-1.11.0        | 1.1 MB    | ###################################################################################################### | 100%
shapely-1.8.0        | 373 KB    | ###################################################################################################### | 100%
pygments-2.11.2      | 796 KB    | ###################################################################################################### | 100%
importlib-metadata-4 | 32 KB     | ###################################################################################################### | 100%
harfbuzz-2.9.1       | 2.0 MB    | ###################################################################################################### | 100%
pyqt-5.12.3          | 22 KB     | ###################################################################################################### | 100%
debugpy-1.5.1        | 2.0 MB    | ###################################################################################################### | 100%
pytest-6.2.5         | 432 KB    | ###################################################################################################### | 100%
mistune-0.8.4        | 54 KB     | ###################################################################################################### | 100%
llvm-openmp-12.0.1   | 2.8 MB    | ###################################################################################################### | 100%
terminado-0.12.1     | 28 KB     | ###################################################################################################### | 100%
zipp-3.7.0           | 12 KB     | ###################################################################################################### | 100%
yaml-0.2.5           | 87 KB     | ###################################################################################################### | 100%
urllib3-1.26.8       | 100 KB    | ###################################################################################################### | 100%
pyqt-impl-5.12.3     | 5.9 MB    | ###################################################################################################### | 100%
setuptools-60.5.0    | 1.0 MB    | ###################################################################################################### | 100%
blas-2.112           | 12 KB     | ###################################################################################################### | 100%
cffi-1.15.0          | 225 KB    | ###################################################################################################### | 100%
jsonschema-4.4.0     | 57 KB     | ###################################################################################################### | 100%
pyqtwebengine-5.12.1 | 175 KB    | ###################################################################################################### | 100%
x265-3.5             | 6.7 MB    | ###################################################################################################### | 100%
libglib-2.70.2       | 3.1 MB    | ###################################################################################################### | 100%
wxpython-4.1.1       | 21.3 MB   | ###################################################################################################### | 100%
pandoc-2.17          | 12.7 MB   | ###################################################################################################### | 100%
pygpu-0.7.6          | 664 KB    | ###################################################################################################### | 100%
argon2-cffi-bindings | 34 KB     | ###################################################################################################### | 100%
docutils-0.17.1      | 760 KB    | ###################################################################################################### | 100%
imageio-2.13.5       | 3.2 MB    | ###################################################################################################### | 100%
pathlib2-2.3.6       | 35 KB     | ###################################################################################################### | 100%
expat-2.4.2          | 182 KB    | ###################################################################################################### | 100%
pyzmq-22.3.0         | 501 KB    | ###################################################################################################### | 100%
ffmpeg-4.4.1         | 10.0 MB   | ###################################################################################################### | 100%
pysocks-1.7.1        | 28 KB     | ###################################################################################################### | 100%
glib-2.70.2          | 437 KB    | ###################################################################################################### | 100%
coverage-6.2         | 232 KB    | ###################################################################################################### | 100%
gst-plugins-base-1.1 | 2.6 MB    | ###################################################################################################### | 100%
importlib_metadata-4 | 4 KB      | ###################################################################################################### | 100%
qtpy-2.0.0           | 38 KB     | ###################################################################################################### | 100%
decorator-5.1.1      | 12 KB     | ###################################################################################################### | 100%
werkzeug-2.0.1       | 219 KB    | ###################################################################################################### | 100%
notebook-6.4.7       | 6.2 MB    | ###################################################################################################### | 100%
wheel-0.37.1         | 31 KB     | ###################################################################################################### | 100%
scipy-1.7.3          | 21.8 MB   | ###################################################################################################### | 100%
grpcio-1.42.0        | 2.3 MB    | ###################################################################################################### | 100%
geos-3.10.1          | 1.4 MB    | ###################################################################################################### | 100%
argon2-cffi-21.3.0   | 15 KB     | ###################################################################################################### | 100%
trimesh-3.9.39       | 513 KB    | ###################################################################################################### | 100%
xorg-libxfixes-5.0.3 | 18 KB     | ###################################################################################################### | 100%
pluggy-1.0.0         | 25 KB     | ###################################################################################################### | 100%
cytoolz-0.11.2       | 407 KB    | ###################################################################################################### | 100%
jupyter_core-4.9.1   | 80 KB     | ###################################################################################################### | 100%
nss-3.74             | 2.1 MB    | ###################################################################################################### | 100%
fsspec-2022.1.0      | 91 KB     | ###################################################################################################### | 100%
nbclient-0.5.10      | 63 KB     | ###################################################################################################### | 100%
libva-2.13.0         | 165 KB    | ###################################################################################################### | 100%
mock-4.0.3           | 51 KB     | ###################################################################################################### | 100%
python-utils-3.0.0   | 19 KB     | ###################################################################################################### | 100%
pyyaml-6.0           | 187 KB    | ###################################################################################################### | 100%
mysql-common-8.0.27  | 1.8 MB    | ###################################################################################################### | 100%
h5py-2.10.0          | 1.1 MB    | ###################################################################################################### | 100%
charset-normalizer-2 | 34 KB     | ###################################################################################################### | 100%
indexed_gzip-1.6.4   | 645 KB    | ###################################################################################################### | 100%
tornado-6.1          | 642 KB    | ###################################################################################################### | 100%
widgetsnbextension-3 | 1.3 MB    | ###################################################################################################### | 100%
markupsafe-2.0.1     | 22 KB     | ###################################################################################################### | 100%
prettytable-3.0.0    | 25 KB     | ###################################################################################################### | 100%
qtconsole-base-5.2.2 | 90 KB     | ###################################################################################################### | 100%
mako-1.1.6           | 58 KB     | ###################################################################################################### | 100%
pango-1.48.10        | 400 KB    | ###################################################################################################### | 100%
nbconvert-6.4.0      | 551 KB    | ###################################################################################################### | 100%
mysql-libs-8.0.27    | 1.9 MB    | ###################################################################################################### | 100%
fslpy-3.8.1          | 3.6 MB    | ###################################################################################################### | 100%
pywavelets-1.2.0     | 4.4 MB    | ###################################################################################################### | 100%
svt-av1-0.8.7        | 2.8 MB    | ###################################################################################################### | 100%
imgaug-0.4.0         | 833 KB    | ###################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: /
SafetyError: The package for keras located at /home/mhbourget/miniconda/pkgs/keras-2.3.1-py37_0
appears to be corrupted. The path 'etc/conda/activate.d/keras_activate.sh'
has an incorrect size.
  reported size: 380 bytes
  actual size: 381 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::tensorboard-1.13.1-py37_0, conda-forge/linux-64::tensorflow-base-1.13.1-py37h5ece82f_5
  path: 'bin/tensorboard'



done
Executing transaction: | b''
/ b'Enabling notebook extension jupyter-js-widgets/extension...\n      - Validating: \x1b[32mOK\x1b[0m\n'
done
Ran pip subprocess with arguments:
['/home/mhbourget/miniconda/envs/ads_venv_test2/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/mhbourget/code/axondeepseg/condaenv.p3e77me4.requirements.txt']
Pip subprocess output:
Collecting opencv-contrib-python
  Downloading opencv_contrib_python-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (66.6 MB)
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.5.5.62-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (47.7 MB)
Requirement already satisfied: numpy>=1.14.5 in /home/mhbourget/miniconda/envs/ads_venv_test2/lib/python3.7/site-packages (from opencv-contrib-python->-r /home/mhbourget/code/axondeepseg/condaenv.p3e77me4.requirements.txt (line 1)) (1.21.5)
Installing collected packages: opencv-python-headless, opencv-contrib-python
Successfully installed opencv-contrib-python-4.5.5.62 opencv-python-headless-4.5.5.62

#
# To activate this environment, use
#
#     $ conda activate ads_venv_test2
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
</details>

There is also an error about Keras at the end.
Despite the error, after installing ADS, all the tests passed without errors.

**Comment by mathieuboudreau** [comment]
Thanks! Yeah, I think moving to V4 will solve these installation lags, there's a few packages in V3 that take a very very long time to resolve in Conda, and they're not included anymore in V4

**Comment by mathieuboudreau** [comment]
With the release of version 4.0 of AxonDeepSeg, some of the packages causing long download and conda package resolutions have been removed. As such, last night the scheduled tests passed (https://github.com/neuropoly/axondeepseg/actions/runs/1793274136), whereas they had failed the other days earlier in the week. I think we can close this PR now, as it is no longer needed.

**Pull request closed without merging**
