### PR TITLE
Update links videos

### PR DESCRIPTION
**Pull request by alexfoias**
Requested on: https://neuropoly.slack.com/archives/CB0KLDR09/p1635106787007200

We will also have to remove the old videos from youtube:

https://youtu.be/qzWeG5vaVyo
https://youtu.be/dz2LqQ5LpIo

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@alexfoias the RTD build passes, but the videos aren't being displayed. Syntax issue (e.g. closing divs? not using youtube shortened link?)?
Screen Shot 2021-11-02 at 10 25 25 PM
Screen Shot 2021-11-02 at 10 25 21 PM

**Comment by mathieuboudreau** [comment]
Hum, despite with my changes our embedded videos matching exactly the same way we've did it in qMRLab ([code](https://github.com/qMRLab/documentation/blame/master/source/index.rst), [RTD](https://qmrlab.readthedocs.io/en/master/?version=latest)), they're not displaying for us correctly here.

Hmm

**Comment by mathieuboudreau** [comment]
No warnings in the build logs: https://readthedocs.org/projects/axondeepseg/builds/15166637/

**Comment by mathieuboudreau** [comment]
I went another route and used SCT's format for these calls (no divs), it seems to work now.

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blame/081078d85c852afede913064ef7f4d9e45623f46/documentation/source/user_section/fsleyes.rst#L37-L39

**Comment by mathieuboudreau** [comment]
Ok, with the new syntax the videos display correctly.

Screen Shot 2021-11-03 at 1 03 01 AM
Screen Shot 2021-11-03 at 1 02 53 AM

**Review by mathieuboudreau — APPROVED** [review]
Videos display as desired, thanks @alexfoias !

**Comment by alexfoias** [comment]
@mathieuboudreau can I remove the old videos ?

https://youtu.be/qzWeG5vaVyo
https://youtu.be/dz2LqQ5LpIo

**Comment by mathieuboudreau** [comment]
@alexfoias ask on the slack channel; I think so, but am not 100% sure.

**Pull request merged**
