### PR TITLE
Added a selection for the axon shape in FSLeyes

### LINKED ISSUE #432: FSLeyes: Implement Ellipse Minor Axis
Once PR #399 is merged, we wish to implement the ellipse minor axis on our ADS FSLeyes plugin. The purpose of this issue to initiate discussions on how do we wish to display the choice of axon shape to our users(  whether they wish to consider the shape of axons as an `ellipse` or `circle`).

**Screenshot of the ADSControl, so we can easily reference to it while brainstorming the design choices of axon shape.**

image

Any suggestions/feebacks are welcome. 

Here are some of my suggestions:- 

1. Similar to the `Select the modality` dropdown, we can add a dropdown/radio button ( `Select the axon shape` where 2 options would be - `ellipse`  and `circle`) in the ADSControl just before the **`Compute Morphometrics`** button.
2. Second option that I thought of was once an user clicks **`Compute Morphometrics`** button, we can ask to input the axon shape ( the input can be either be a dropdown or radio button, similar to option 1)

### PR DESCRIPTION
**Pull request by Stoyan-I-A**
- Fixes #432 
- Should be implemented when #399 is merged

### CODE REVIEW

**Comment by vs74** [comment]
@Stoyan-I-A we have merged PR #399. Just letting you know so you can work on this PR.

Thanks!

**Comment by Stoyan-I-A** [comment]
I would like https://github.com/neuropoly/axondeepseg/pull/507 to be merged before adding more options in the settings menu.

**Comment by vasudev-sharma** [comment]
FYI PR #507 has been merged.

**Comment by Stoyan-I-A** [comment]
I'm thinking of creating a new PR that resolves #432 because this one is pretty old and I have made changes to the plugin file in between.

**Comment by Stoyan-I-A** [comment]
I created a new PR for this: https://github.com/neuropoly/axondeepseg/pull/541

**Pull request closed without merging**
