### PR TITLE
Remove PyPI install instructions from RTD

### PR DESCRIPTION
**Pull request by mariehbourget**
Related to #368 
Removed the instructions for the installation of the stable release via PyPI in RTD.
The only installation methods are now the development version via git clone, or via a link to download a zip from github.

### CODE REVIEW

**Review by jcohenadad — APPROVED** [review]
i've made slight modifications-- the rest looks ok 👍

**Comment by mariehbourget** [comment]
If git is no longer "optional", we should also remove the link for download and the note about the main folder having a different name than "axondeepseg" i.e. the only option will now be to clone via git.
@jcohenadad, can you confirm that this is what you want and I'll make the changes, thanks!

**Comment by jcohenadad** [comment]
> If git is no longer "optional", we should also remove the link for download and the note about the main folder having a different name than "axondeepseg" i.e. the only option will now be to clone via git.
> @jcohenadad, can you confirm that this is what you want and I'll make the changes, thanks!

makes sense to me-- it also simplifies the install procedure (the less text there is, the happier the users).  @mathieuboudreau are you ok with that?

**Comment by mariehbourget** [comment]
> > If git is no longer "optional", we should also remove the link for download and the note about the main folder having a different name than "axondeepseg" i.e. the only option will now be to clone via git.
> > @jcohenadad, can you confirm that this is what you want and I'll make the changes, thanks!
> 
> makes sense to me-- it also simplifies the install procedure (the less text there is, the happier the users). @mathieuboudreau are you ok with that?

@mathieuboudreau, is it ok with you if we remove the link for download?

**Comment by mathieuboudreau** [comment]
Sounds good to me !

**Comment by mariehbourget** [comment]
This PR is ready for re-review.

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
