### PR TITLE
Add test for morphometrics consistency

### PR DESCRIPTION
**Pull request by hermancollin**
## Checklist

- [x] I've given this PR a concise, self-descriptive, and meaningful title
- [x] I've linked relevant issues in the PR body
- [x] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [x] I've added relevant tests for my contribution
- [x] I've updated the documentation and/or added correct docstrings
- [x] I've assigned a reviewer
- [x] I've consulted [ADS's internal developer documentation](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution) to ensure my contribution is in line with any relevant design decisions

## Description

This PR adds a unit test that compares morphometrics values computed from `__test_files__/__test_demo_files__/image.png` with a reference axonlist.npy file added in the testing data.

## Linked issues

Discussed in #589

### CODE REVIEW

**Comment by hermancollin** [comment]
Converted to draft until I figure out why the checks are failing. The cause of the failure is the new test, which is weird since it runs fine locally.

**Comment by mathieuboudreau** [comment]
@hermancollin are there any NaN's in the morphometrics? You can't compare two arrays easily if one contains a NaN, it was giving me a lot of headaches a few weeks ago. If this is the case, I'll share a "hack" to help you test it.

**Comment by hermancollin** [comment]
> @hermancollin are there any NaN's in the morphometrics? You can't compare two arrays easily if one contains a NaN, it was giving me a lot of headaches a few weeks ago. If this is the case, I'll share a "hack" to help you test it.

@mathieuboudreau I don't see any NaN values in the file. Besides, I used your method to assess equality:
```python
for row_ref, row_new in zip(reference_stats_array, new_stats_array):
   if any(math.isnan(val) for val in row_ref.values()) == False and any(math.isnan(val) for val in row_new.values()) == False:
      assert np.array_equal(row_ref, row_new)
```
So IIUC it should still work with NaN values.

I tried running the checks again and weirdly enough they are only successful in linux.

**Comment by mathieuboudreau** [comment]
Gotcha! Thanks!

**Comment by hermancollin** [comment]
So I switched the `np.array_equal` assertion to `np.allclose`, which allows a relative/absolute tolerance when checking equality. It seems the test were failing because of some form of numerical instability. For example, some morphometrics values were slightly different wrt. their last digit. I am not sure what is causing this and it may not be a problem.

Also I used an absolute tolerance of 1e-11 but it's somewhat arbitrary and we might prefer using relative tolerance.

**Comment by mathieuboudreau** [comment]
Excellent - great solution @hermancollin !

**Pull request merged**
